config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :user_interests

  resources :users do
    resources :requests, only: [:create, :destroy]
  end

  resources :requests do
    collection do
      get :my_requests
    end
    member do
      get :accept
      get :ignore
    end
   resources :chatrooms, only: [:create, :show]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :dashboard, only: :index

  # resources :requests do
  #   member do
  #     get :accept
  #     get :ignore
  #   end
  # end

  # collection do
  #   get :my_mentors
  #   get :my_meentees
  # end
  mount ActionCable.server => "/cable"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
# skip_before_action :authenticate_user!
# before_action :authenticate_user!
  def index
    @user = current_user
    if current_user.mentor
      @my_requests = current_user.requests_as_receiver
    else
      @my_requests = current_user.requests_as_asker.where(status: "Accepted")
    end
    @my_messages = @my_requests.where(status: "Accepted").map do |request|
      request.chatroom.messages.where.not(user: current_user).last
    end
  end
end

app/views/dashboard/index.html.erb
<!-- Head -->
<% content_for :meta_title, " Femnet | Dashboard" %>

<h1>Hi, <%= current_user.name %>!</h1>

<!-- Profile overview -->

<div class="flexbox">
<div class="information-wrapper">
  <% if @user.photo.present? %>
    <%= cl_image_tag @user.photo.key, id: "dashboard-profile-photo"%>
  <% else %>
    <%= image_tag "businesswoman-2.png", id: "dashboard-profile-photo"%>
  <% end %>
  <div class="card-left">
  <div class="personal-information">
    <% if @user.mentor %>
      <p>Mentor</p>
    <% else %>
      <p>Mentee</p>
    <% end %>
    <h2><%= @user.name %></h2>
    <ul class="personal-list">
      <li><%= image_tag "shape-03.png" %><strong><%= @user.age %></strong> years old</li>
      <li><%= image_tag "shape-03.png" %>based in <strong><%= @user.city %></strong></li>
      <li><%= image_tag "shape-03.png" %>working in <strong><%= @user.profession %></strong></li>
    </ul>
  </div>
  </div>



<!-- Messages overview -->

<div class="card-right" id= "card-messages">
  <h3><%= image_tag "communication.png", class: "dashboard-icon"%> Your Messages</h3>
  <div class="messages-overview">
  <% if @my_messages.first.nil?  %>
  <div class = no-messages>
    <h2>You dont have any messages </h2>
    <%= link_to "Find your Mentor", users_path, class: "button-primary", id:"header-btn"%>
  </div>
  <% else %>
  <div class="dashboard-messages">
    <% @my_messages.each do |message| %>
      <% if message %>
      <div class="dashboard-message-container">
        <small><%= message.created_at.strftime("%m/%d/%Y at %l:%M%p")%></small></br>
        <span><%= message.user.name %>:</span>
        <p><%= message.content %></p>
        <div class = "message-button">
        <%= link_to "Keep chatting" , request_chatroom_path(message.chatroom.request, message.chatroom), class: "button-primary" %>
        </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <% end %>
  </div>
</div>

</div>


<!-- Mentors/Mentees overview -->

<div class="card-mentors-wrapper">
  <% if current_user.mentor %>
    <h3><%= image_tag "growth.png", class: "dashboard-icon"%> Your accepted Mentees</h3>
    <div class = "card-mentors">
         <% @my_requests.each do |request| %>
            <% if request.status === "Accepted" %>
              <div class="dashboard-cards">
                <% if request.asker.photo.present? %>
                  <%= cl_image_tag request.asker.photo.key, id: "profile-photo"%>
                <% else %>
                  <%= image_tag "businesswoman-2.png", id: "profile-photo"%>
                <% end %>
                <div id="information">
                  <p><strong><%= request.asker.city %></strong></br></p>
                  <h3><%= request.asker.name %></h3>
                  <p><strong><%= request.asker.profession %></strong></br></p>
                  <div class="read-more-button">
                  <%= image_tag "communication.png", id: "dashboard-icon-card"%><%= link_to "Let's chat" , request_chatroom_path(request, request.chatroom), class: "button-primary" %><br><br>
                  <%= image_tag "match.png", id: "dashboard-icon-card"%><%= link_to "Read More", user_path(request.receiver), class: "button-primary" %>
                </div>
                </div>
                </div>
              </div>
            <% end %>
        <% end %>
    </div>

  <% else %>
    <h3><%= image_tag "growth.png", class: "dashboard-icon"%> Your accepted Mentors</h3>
    <div class = "card-mentors">
        <% current_user.requests_as_asker.where(status: "Accepted").each do |request| %>
          <div class="dashboard-cards">
            <% if request.receiver.photo.present? %>
              <%= cl_image_tag request.receiver.photo.key, id: "profile-photo"%>
            <% else %>
              <%= image_tag "businesswoman-2.png", id: "profile-photo"%>
            <% end %>
            <div id="information">
              <p><strong><%= request.receiver.city %></strong></br></p>
              <h3><%= request.receiver.name %></h3>
              <p><strong><%= request.receiver.profession %></strong></br></p><br>
              <div class="read-more-button">
              <%= image_tag "communication.png", id: "dashboard-icon-card"%><%= link_to "Let's chat" , request_chatroom_path(request, request.chatroom), class: "button-primary" %><br><br>
              <%= image_tag "match.png", id: "dashboard-icon-card"%><%= link_to "Read More", user_path(request.receiver), class: "button-primary" %>
            </div>
          </div>
          </div>
        <% end %>
    </div>
  <% end %>
</div>


<!-- Requests overview -->

<div class="card-requests">
  <h3><%= image_tag "match.png", class: "dashboard-icon"%> Your pending Requests</h3>
    <% if current_user.mentor %>
      <% @my_requests.each do |request| %>
        <% if request.status === "Pending" %>
        <div class="dashboard-user-card" id= "user-card-mentor">
          <h2><%= image_tag "shape-03.png" %><%= request.asker.name %></h2>
          <div>
            <%= link_to "Accept", accept_request_path(request),class: "btn btn-info" %> <%= link_to "Ignore", ignore_request_path(request), class: "btn btn-info" ,id: "ignore"%>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
       <% current_user.requests_as_asker.where(status: "Pending").each do |request| %>
        <div class="dashboard-user-card">
          <h2><%= image_tag "shape-03.png" %><%= request.receiver.name %></h2>
        </div>
    <% end %>
  <% end %>
</div>