config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :user_interests

  resources :users do
    resources :requests, only: [:create, :destroy]
  end

  resources :requests do
    collection do
      get :my_requests
    end
    member do
      get :accept
      get :ignore
    end
   resources :chatrooms, only: [:create, :show]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :dashboard, only: :index

  # resources :requests do
  #   member do
  #     get :accept
  #     get :ignore
  #   end
  # end

  # collection do
  #   get :my_mentors
  #   get :my_meentees
  # end
  mount ActionCable.server => "/cable"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :age, inclusion: 16..99
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :answer1, :answer2, :answer3, length: { in: 100..500 }

  has_many :user_interests, dependent: :destroy
  has_many :interests, through: :user_interests, dependent: :destroy

  has_many :requests_as_asker, source: :requests, class_name: "Request", foreign_key: :asker, dependent: :destroy
  has_many :requests_as_receiver, source: :requests, class_name: "Request", foreign_key: :receiver_id, dependent: :destroy

  has_one_attached :photo
  has_one_attached :resume

  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?

  scope :filter_by_profession, -> (profession_array) { where profession: profession_array }
  scope :filter_by_mentor, -> (user) { where(mentor: true).where.not(id: user) }
  scope :filter_by_interest, -> (interest_array) { joins(:user_interests).where(user_interests: { interest: interest_array }).distinct }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @interests = Interest.all

    if current_user.mentor == false
      if params[:professions].present? || params[:query].present? || params[:interests].present?
        #raise
        # first filter by search
        @users = policy_scope(User.where(mentor: true).geocoded)
        sql_query = "name ILIKE :query OR city ILIKE :query "
        @users = policy_scope(User.where(sql_query, query: "%#{params[:query]}%")).filter_by_mentor(current_user) if params[:query].present?

        # second filter by filter selection
        @users = @users.filter_by_profession(params[:professions]) if params[:professions].present?

        @users = @users.filter_by_interest(params[:interests].map { |id| id.to_i }) if params[:interests].present?

      else
        @users = policy_scope(User.where(mentor: true).geocoded)
      end
    else
      @users = policy_scope(User.where(mentor: false).geocoded)
    end
    @request = Request.new

    prng = Random.new

    @markers = @users.map do |user|
        {
          lat: user.latitude - prng.rand(0.001..0.02),
          lng: user.longitude - prng.rand(0.0001..0.02),
          infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
          image_url: helpers.asset_url('map-marker.png')
        }
    end

  end

  def show
    @user = User.find_by_id(params[:id])
    @user_interests = UserInterest.all
    authorize @user
    @request = Request.new
    @status = current_user.requests_as_asker.find_by(receiver: @user)

    # 1 find all requests of current user

    # 2 within all requests find request where @user exist as receiver
    # if exist = show status for request
    # else
    #  redirect_to my_requests_requests_path
    # end
  end

  def edit
  end

  def update
    @user = current_user
    if @user.update(user_params)
      # Sign in the user by passing validation in case their password changed
      # bypass_sign_in(@user)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'Your Profile was successfully deleted.'
  end

  private

  def set_user
    @user = User.find_by_id(params[:id])
    authorize @user
  end

  def user_params
    # NOTE: Using `strong_parameters` gem
    params.require(:user).permit(:name, :profession, :age, :photo, :city, :answer1, :answer2, :answer3, :resume)
  end

end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class = "container">
    <div class="edit-form-inputs">
      <%= f.input :name%>
      <%= f.input :photo, as: :file%>
      <%= f.input :age %>
      <%= f.input :profession, collection: ["Brand & Public Relations",
                    "Consulting",
                    "Data Science & Analytics",
                    "Entrepreneurship",
                    "Finance, Accounting & Controlling",
                    "Freelancing",
                    "Human Ressources & Recruiting",
                    "Infrastructures & Security",
                    "Leadership & Management",
                    "Marketing & Growth",
                    "Product Management",
                    "Sales",
                    "Software Engineering",
                    "Strategy & Business Development",
                    "Sustainability",
                    "UX, Design & User Research",
                    "Web Development"]%>
      <%= f.input :city %>
      <%= f.input :answer1, label: 'Who are you, what defines you and what have you accomplished so far?'%>
      <%= f.input :answer2, label: 'Where do you see yourself in the future?'%>
      <%= f.input :answer3, label: 'What are you expecting from FemNet?'%>
      <%= f.input :resume, as: :file %>

      <%= f.submit class: "btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/_info_window.html.erb
<h2><%= user.name %></h2>
<p><% if user.mentor %>
    Mentor
    <% end %>
  </p>
<p><%= user.city %></p>
<p><%= user.profession %></p>
<p><strong>(<%= user.age %>)</strong></p>

app/views/users/edit.html.erb
<!-- Head -->

<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]} | Edit Profile " %>

<!-- Body -->


<h1>Edit your profile</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<!-- Head -->

<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]} | All mentors " %>

<!-- Body -->

  <% professions = ["Brand & Public Relations",
                  "Consulting",
                  "Data Science & Analytics",
                  "Entrepreneurship",
                  "Finance, Accounting & Controlling",
                  "Freelancing",
                  "Human Ressources & Recruiting",
                  "Infrastructures & Security",
                  "Leadership & Management",
                  "Marketing & Growth",
                  "Product Management",
                  "Sales",
                  "Software Engineering",
                  "Strategy & Business Development",
                  "Sustainability",
                  "UX, Design & User Research",
                  "Web Development"] %>

<div class="main-container">
  <div class="search-container">
  <p><strong>Find your Mentor</strong></p>
    <%= form_tag users_path, method: :get do %>
    <%= text_field_tag :query,
       params[:query],
       class: "form-control",
       id: "searchfield",
       placeholder: "Search for name or city"
       %>
    <ul class="filter-professions">
       <p><strong>Profession</strong></p>
       <% professions.each do |profession| %>
       <li>
          <%= check_box_tag 'professions[]', profession -%>
          <%= profession -%>
       </li>
       <% end %>
    </ul>
    <ul class="filter-interests">
       <p><strong>Interests</strong></p>
       <% @interests.each do |interest| %>
       <li>
          <%= check_box_tag 'interests[]', interest.id -%>
          <%= interest.name -%>
       </li>
       <% end %>
    </ul>
    <%= submit_tag "Search", class: "button-primary", id: "search-btn"%>
    <% end %>
</div>

  <div class="card-container">
    <ul>
      <li><a class="switch-button" onclick="getElementById('card-wrapper').style.display = ''; getElementById('map').style.display = 'none';"><i class="fa fa-list"></i></a></li>
      <li><a class="switch-button" onclick="getElementById('card-wrapper').style.display = 'none'; getElementById('map').style.display = 'block';"><i class="fa fa-map"></i></a></li>
    </ul>
    <p id="search-results"><strong><%= @users.count %></strong> result(s) found</p>

  <div class="all-cards" id="card-wrapper">

  <% @users.each do |user| %>
    <div class="card">
       <% if user.photo.present? %>
          <%= cl_image_tag user.photo.key, id: "profile-photo"%>
       <% else %>
          <%= image_tag "businesswoman-2.png", id: "profile-photo"%>
       <% end %>
       <div class="information">
          <p><%= user.city %></p>
          <h3><%= user.name %></h3>
          <p><strong><%= user.profession %></strong></br></p>
       <div class="interest-information">
          <% if user.user_interests.present? %>
            <% user.user_interests.each do |interest| %>
              <div id="name-interest">
                <%= interest.interest.name %></br>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="read-more-button">
       <%= link_to "Read More", user_path(user), class: "button-primary" %>
      </div>
      </div>
      <% end %>
    </div>

  <div class="map" id="map"
       style="height: 1400px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>


</div>

app/views/users/show.html.erb
<!-- Head -->
<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]} | #{@user.name} " %>

<!-- Body -->

<% if current_user == @user %>
  <div class="wrapper-button">
  <%= link_to "Edit Profile", edit_user_path(current_user), class: "button-primary"%>
  <%= link_to "Delete Profile", @user, method: :delete, data: { confirm: 'Are you sure you want to delete your Profile?' }, class: "button-primary"%>
  </div>
<% end %>

<div class="flexbox">
  <div class="information-wrapper">
    <% if @user.photo.present? %>
      <%= cl_image_tag @user.photo.key, id: "profile-photo"%>
    <% else %>
      <%= image_tag "businesswoman-2.png", id: "profile-photo"%>
    <% end %>
    <div class="card-left">
    <div class="personal-information">
      <% if @user.mentor %>
        <p>Mentor</p>
      <% else %>
        <p>Mentee</p>
      <% end %>
      <h2><%= @user.name %></h2>
      <ul class="personal-list">
        <li><%= image_tag "shape-03.png" %><strong><%= @user.age %></strong> years old</li>
        <li><%= image_tag "shape-03.png" %>based in <strong><%= @user.city %></strong></li>
        <li><%= image_tag "shape-03.png" %>working in <strong><%= @user.profession %></strong></li>
      </ul>

     <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
   See CV
  </button>
</div>

  <div class="card-right">
    <div class="question">
      <div class="wrapper-number">
        <%= image_tag "number-01.png" %>
      </div>
      <div class="wrapper-questions">
        <p><strong>Who are you, what defines you and what have you </br>accomplished so far?</strong></br><%= @user.answer1 %></p>
      </div>
    </div>
    <div class="question">
      <div class="wrapper-number">
        <%= image_tag "number-02.png" %>
      </div>
      <div class="wrapper-questions">
        <p><strong>Where do you see yourself in the future?</strong></br><%= @user.answer2 %></p>
      </div>
    </div>
    <div class="question">
      <div class="wrapper-number">
        <%= image_tag "number-03.png" %>
      </div>
      <div class="wrapper-questions">
      <p><strong>What are you expecting from FemNet?</strong></br><%= @user.answer3 %></p>
      </div>
    </div>
  </div>
</div>

<%= image_tag 'shape-01.png', id: "background-shape-right"%>

<div class="card-interests">
<h2>Topics, I am interested in</h2>
  <ul>
    <% if @user.user_interests.present? %>
      <% @user.user_interests.each do |interest| %>
        <li>
          <strong><%= interest.interest.name %></strong>

          <% if interest.score > 4 %>
            <%= image_tag 'score-05.png', class: "score-image"%>
          <% elsif interest.score > 3%>
            <%= image_tag 'score-04.png', class: "score-image"%>
          <% elsif interest.score > 2%>
            <%= image_tag 'score-03.png', class: "score-image"%>
          <% elsif interest.score > 1%>
            <%= image_tag 'score-02.png', class: "score-image"%>
          <% else %>
            <%= image_tag 'score-01.png', class: "score-image"%>
          <% end %>

          <% if current_user == @user %>
            <div class="button-wrapper">
              <%= link_to "Edit", edit_user_interest_path(interest), class: "edit-btn"%>
              <%= link_to "Delete", interest, method: :delete, data: { confirm: 'Are you sure you want to delete this Interest?' }, class: "edit-btn"%>
            </div>
          <% end %>
        </li>
      <% end %>
    <% else %>
      <li><em>no interests added yet</em></li>
    <% end %>
    <% if current_user == @user %>
    <li><%= link_to "Add Interests", new_user_interest_path, class: "button-primary"%></li>
    <% end %>
</ul>
</div>

<div class="mentor-request">
  <% if current_user != @user %>
    <h2>Want to get </br>in touch?</h2>
    <% if current_user.mentor %>
      <%= link_to "My requests", my_requests_requests_path %>
    <% else %>
      <% if @status %>
        <p><%= @status.status %></p>
      <% else %>
         <%= simple_form_for([@user, @request]) do |f| %>
        <div class="form-actions" id="create-r">
        <%= f.submit class: "button-primary", id: "create-request"%>
        </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" id="modal-size" role="document">
      <div class="modal-content" id="modal-background">
        <div class="modal-header" id="modal-header">
          <button type="button" class="close" id="close-button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if @user.resume.present?  %>
            <%= cl_image_tag @user.resume.key, format: :png, id: "resume"%>
          <% else %>
            <p>No CV available</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>