config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :user_interests

  resources :users do
    resources :requests, only: [:create, :destroy]
  end

  resources :requests do
    collection do
      get :my_requests
    end
    member do
      get :accept
      get :ignore
    end
   resources :chatrooms, only: [:create, :show]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :dashboard, only: :index

  # resources :requests do
  #   member do
  #     get :accept
  #     get :ignore
  #   end
  # end

  # collection do
  #   get :my_mentors
  #   get :my_meentees
  # end
  mount ActionCable.server => "/cable"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <%= image_tag 'footer-line.png', class: "footer-vector"%>

  <div class="footer-femnet">
    <div class="footer-links">
        <p><strong>About</strong></p><br>
        <p>Terms</p><br>
        <p>Privacy</p>
    </div>
    <div class="footer-social">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-femnet.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_index_path , class: "nav-link"%>
        </li>
         <% if current_user.mentor %>
            <li class="nav-item">
              <%= link_to "Messages", my_requests_requests_path, class: "nav-link" %>
            </li>
          </li>
         <% else %>
         <%= link_to "Find your Mentor", users_path , class: "nav-link" %>
         <li class="nav-item">
          <%= link_to "Messages", my_requests_requests_path, class: "nav-link" %>
        </li>
         <% end %>
        <li class="nav-item dropdown">
          <% if current_user.photo.present? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag "businesswoman-2.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>